I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 273, in script
    hide alistair with Dissolve(.5)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 273, in script
    hide alistair with Dissolve(.5)
  File "/Users/Emilie/Desktop/renpy-6.99.14.2-sdk/renpy/ast.py", line 1337, in execute
    renpy.exports.with_statement(trans, paired)
  File "/Users/Emilie/Desktop/renpy-6.99.14.2-sdk/renpy/exports.py", line 1413, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/Users/Emilie/Desktop/renpy-6.99.14.2-sdk/renpy/display/core.py", line 2193, in do_with
    clear=clear)
  File "/Users/Emilie/Desktop/renpy-6.99.14.2-sdk/renpy/display/core.py", line 2635, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/Users/Emilie/Desktop/renpy-6.99.14.2-sdk/renpy/display/core.py", line 2972, in interact_core
    new_widget=layers_root)
TypeError: 'Dissolve' object is not callable

Darwin-15.6.0-x86_64-i386-64bit
Ren'Py 6.99.14.2.3333
Test 2018 1.0
Mon May  7 11:13:16 2018
